---
apiVersion: v1
kind: Service
metadata:
  name: ambari-server-sc
  namespace: ambari
  labels:
    app: ambari-server
spec:
  ports:
  - port: 8080
    name: web
  clusterIP: None
  selector:
    app: ambari-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ambari-server
  namespace: ambari
  labels:
    app: ambari-server
spec:
  serviceName: "ambari-server-sc"
  replicas: 1
  selector:
    matchLabels:
      app: ambari-server
  template:
    metadata:
      labels:
        app: ambari-server
    spec:
      containers:
      - name: ambari-server
        securityContext:
          privileged: true
        image: abhinavsinha001/ambari-server:2.2.1-test
        volumeMounts:
            - name: ambari-conf
              mountPath: /etc/systemd/system/ambari-server.service.d
            - name: ambari-scripts
              mountPath: /scripts
        env: 
          - name: USE_CONSUL_DNS
            value: "false"
          - name: AMBARI_SERVER
            value: ambari-server-0.ambari-server-sc.ambari.svc.cluster.local
          - name: AMBARI_HOST
            value: ambari-server-0.ambari-server-sc.ambari.svc.cluster.local

        ports:
        - containerPort: 8080
      volumes:
          - name: ambari-conf
            configMap: 
                name: ambari-server
          - name: ambari-scripts
            configMap: 
                name: ambari-server-scripts


