apiVersion: v1
kind: Service
metadata:
  name: mapred-ui
  namespace: ambari
spec:
  clusterIP: None
  selector:
    app: amb-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 19888 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: mapred-ui
  namespace: ambari
spec:
  rules:
  - host: mapred-ny7-arch.pubmatic.com
    http:
      paths:
      - backend:
          serviceName: mapred-ui
          servicePort: 80
        path: /
