---
apiVersion: v1
kind: Service
metadata:
  name: ambari-server-web-lb
  namespace: ambari-274
  labels:
    app: ambari-server
spec:
  ports:
    # the port that this service should serve on
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: ambari-server
