apiVersion: v1
kind: Service
metadata:
  name: namenode-ui
  namespace: ambari-274
spec:
  clusterIP: None
  selector:
    name: amb-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50070 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: namenode-ui
  namespace: ambari-274
spec:
  rules:
  - host: hdfs-274-ny7-arch.pubmatic.com
    http:
      paths:
      - backend:
          serviceName: namenode-ui
          servicePort: 80
        path: /
